language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python tests.py
services:
  - postgresql
before_script:
  - psql -c 'create database todo_api_testing;' -U postgres
