"""Change password to hash

Revision ID: 49cd7a5a1015
Revises: b0ac1a366391
Create Date: 2018-05-10 19:02:02.138912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cd7a5a1015'
down_revision = 'b0ac1a366391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash', sa.String(length=60), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('user', 'hash')
    # ### end Alembic commands ###
