"""Add is_completed attribute to Todo

Revision ID: caf8cbb2bf01
Revises: 4c9cb436e212
Create Date: 2018-05-12 17:14:14.319321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf8cbb2bf01'
down_revision = '4c9cb436e212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'is_completed')
    # ### end Alembic commands ###
